apiVersion: v1
kind: Namespace
metadata:
  name: titanic-api
  labels:
    name: titanic-api
    monitoring: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
