apiVersion: v1
kind: ServiceAccount
metadata:
  name: titanic-api-sa
  namespace: titanic-api
  labels:
    app: titanic-api
    app.kubernetes.io/name: titanic-api
    app.kubernetes.io/managed-by: manual
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: titanic-api-role
  namespace: titanic-api
  labels:
    app: titanic-api
rules:
  # Allow reading pod metadata (for OTEL resource attributes)
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: titanic-api-rolebinding
  namespace: titanic-api
  labels:
    app: titanic-api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: titanic-api-role
subjects:
  - kind: ServiceAccount
    name: titanic-api-sa
    namespace: titanic-api
---
# OTEL Collector ServiceAccount and RBAC
apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-collector-sa
  namespace: monitoring
  labels:
    app: otel-collector
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otel-collector-role
  labels:
    app: otel-collector
rules:
  # Read pod and node metrics
  - apiGroups: [""]
    resources: ["nodes", "nodes/proxy", "pods", "events", "services", "configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["deployments", "daemonsets", "replicasets", "statefulsets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otel-collector-rolebinding
  labels:
    app: otel-collector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: otel-collector-role
subjects:
  - kind: ServiceAccount
    name: otel-collector-sa
    namespace: monitoring
---
# Promtail ServiceAccount and RBAC
apiVersion: v1
kind: ServiceAccount
metadata:
  name: promtail-sa
  namespace: monitoring
  labels:
    app: promtail
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: promtail-role
  labels:
    app: promtail
rules:
  - apiGroups: [""]
    resources: ["nodes", "nodes/proxy", "pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: promtail-rolebinding
  labels:
    app: promtail
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: promtail-role
subjects:
  - kind: ServiceAccount
    name: promtail-sa
    namespace: monitoring
