apiVersion: v1
kind: Service
metadata:
  name: promtail
  namespace: monitoring
  labels:
    app: promtail
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: http
    port: 3101
    targetPort: 3101
    protocol: TCP
  selector:
    app: promtail
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: promtail
  namespace: monitoring
  labels:
    app: promtail
    app.kubernetes.io/name: promtail
    app.kubernetes.io/managed-by: manual
spec:
  selector:
    matchLabels:
      app: promtail
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: promtail
        app.kubernetes.io/name: promtail
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3101"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: promtail-sa
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
        fsGroup: 0
      containers:
      - name: promtail
        image: grafana/promtail:2.9.3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3101
          name: http
          protocol: TCP
        args:
          - "-config.file=/etc/promtail/promtail.yaml"
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        volumeMounts:
        - name: promtail-config
          mountPath: /etc/promtail
          readOnly: true
        - name: varlog
          mountPath: /var/log
          readOnly: true
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: journal
          mountPath: /var/log/journal
          readOnly: true
        - name: positions
          mountPath: /tmp
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /ready
            port: 3101
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 3101
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 2
        securityContext:
          allowPrivilegeEscalation: true
          readOnlyRootFilesystem: true
          capabilities:
            add:
              - DAC_READ_SEARCH
      volumes:
      - name: promtail-config
        configMap:
          name: promtail-config
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: journal
        hostPath:
          path: /var/log/journal
      - name: positions
        emptyDir: {}
